[project]
name = "pandas"
source_url = "https://github.com/pandas-dev/pandas.git"
pandas_version = "2.1.1"

[launching_fawltydeps]
fawltydeps_version = "0.13.0"

[experiment_result]
"number of warnings" = 0
imports = [ "s3fs", "boto3", "fastparquet", "Foundation", "pyxlsb", "lxml", "botocore", "_csv", "numexpr", "__main__", "google", "PyQt4", "xlrd", "IPython", "dateutil", "dask", "python_calamine", "odf", "numpy", "numba", "pytz", "AppKit", "fsspec", "scipy", "traitlets", "pyarrow", "pylab", "PyQt5", "tables", "pytest", "markupsafe", "qtpy", "openpyxl", "xarray", "xlsxwriter", "cycler", "typing_extensions", "mpl_toolkits", "sklearn", "hypothesis", "py", "matplotlib", "bs4", "sqlalchemy",]
declared_deps = [ "numpy", "numpy", "numpy", "python-dateutil", "pytz", "tzdata", "hypothesis", "pytest", "pytest-xdist", "pytest-asyncio", "bottleneck", "numba", "numexpr", "scipy", "xarray", "fsspec", "s3fs", "gcsfs", "pandas-gbq", "odfpy", "openpyxl", "pyxlsb", "xlrd", "xlsxwriter", "pyarrow", "pyarrow", "tables", "pyreadstat", "SQLAlchemy", "psycopg2", "SQLAlchemy", "pymysql", "SQLAlchemy", "beautifulsoup4", "html5lib", "lxml", "lxml", "matplotlib", "jinja2", "tabulate", "PyQt5", "qtpy", "zstandard", "dataframe-api-compat", "beautifulsoup4", "bottleneck", "dataframe-api-compat", "fastparquet", "fsspec", "gcsfs", "html5lib", "hypothesis", "jinja2", "lxml", "matplotlib", "numba", "numexpr", "odfpy", "openpyxl", "pandas-gbq", "psycopg2", "pyarrow", "pymysql", "PyQt5", "pyreadstat", "pytest", "pytest-xdist", "pytest-asyncio", "pyxlsb", "qtpy", "scipy", "s3fs", "SQLAlchemy", "tables", "tabulate", "xarray", "xlrd", "xlsxwriter", "zstandard",]
undeclared_deps = [ "AppKit", "Foundation", "IPython", "PyQt4", "__main__", "_csv", "boto3", "botocore", "cycler", "dask", "google", "markupsafe", "python_calamine", "sklearn", "traitlets", "typing_extensions",]
unused_deps = [ "bottleneck", "dataframe-api-compat", "gcsfs", "html5lib", "jinja2", "pandas-gbq", "psycopg2", "pymysql", "pyreadstat", "pytest-asyncio", "pytest-xdist", "tabulate", "tzdata", "zstandard",]

[launching_fawltydeps.settings]
actions = [ "check_undeclared", "check_unused",]
output_format = "json"
code = [ ".repositories/pandas/pandas",]
deps = [ ".repositories/pandas/pandas",]
pyenvs = [ ".repositories/pandas/pandas/venv",]
ignore_undeclared = []
ignore_unused = []
install_deps = false
verbosity = 0
custom_mapping_file = []
