[project]
name = "opencv-python"
source_url = "https://github.com/opencv/opencv-python.git"
version = "0.12.1"

[experiment]
imports = [ "auditwheel", "pip", "skbuild",]
declared_deps = [ "numpy", "numpy", "numpy", "numpy", "numpy", "numpy", "numpy", "numpy", "numpy",]
undeclared_deps = [ "auditwheel", "pip", "skbuild",]
unused_deps = [ "numpy",]
