[project]
name = "pygame"
source_url = "https://github.com/pygame/pygame.git"
version = "0.12.1"

[experiment]
imports = [ "OpenGL", "win32api", "setuptools", "cv2", "win32pipe", "vidcap", "requests", "VideoCapture", "pkg_resources", "win32file", "PyInstaller", "bdist_mpkg_support", "docutils", "sphinx", "Cython", "numpy",]
declared_deps = []
undeclared_deps = [ "Cython", "OpenGL", "PyInstaller", "VideoCapture", "bdist_mpkg_support", "cv2", "docutils", "numpy", "pkg_resources", "requests", "setuptools", "sphinx", "vidcap", "win32api", "win32file", "win32pipe",]
unused_deps = []
