[project]
name = "Kivy"
source_url = "https://github.com/kivy/kivy.git"
Kivy_version = "2.2.1"

[launching_fawltydeps]
fawltydeps_version = "0.13.0"

[experiment_result]
"number of warnings" = 0
imports = [ "coverage", "flask", "watchdog", "docutils", "__main__", "gimpfu", "win32con", "pytest_trio", "mock", "Leap", "picamera", "win32api", "numpy", "oscpy", "setuptools", "pygame", "AppKit", "responses", "testsuite", "pytest", "twisted", "android", "smb", "ffmpeg", "ffpyplayer", "requests", "certifi", "Image", "pygments", "cv2", "enchant", "dbus", "jnius", "ios", "pytest_asyncio", "redis", "pyobjus", "android_mixer", "opencv", "gobject", "gi", "kivy_deps", "trio", "PyInstaller", "PIL", "win32file", "win32gui",]
declared_deps = [ "Kivy-Garden", "docutils", "pygments", "kivy-deps.angle", "kivy-deps.sdl2", "kivy-deps.glew", "pypiwin32", "kivy-deps.angle", "pillow", "requests", "docutils", "pygments", "kivy-deps.angle", "kivy-deps.sdl2", "kivy-deps.glew", "pypiwin32", "pytest", "pytest-cov", "pytest-asyncio", "pytest-timeout", "pytest-benchmark", "pyinstaller", "sphinx", "sphinxcontrib-blockdiag", "sphinxcontrib-seqdiag", "sphinxcontrib-actdiag", "sphinxcontrib-nwdiag", "sphinxcontrib-jquery", "funcparserlib", "flake8", "pre-commit", "responses", "kivy-deps.gstreamer-dev", "kivy-deps.sdl2-dev", "kivy-deps.glew-dev", "pillow", "docutils", "pygments", "ffpyplayer", "kivy-deps.gstreamer", "kivy-deps.angle", "kivy-deps.sdl2", "kivy-deps.glew", "pypiwin32", "kivy-deps.glew", "kivy-deps.gstreamer", "ffpyplayer", "kivy-deps.gstreamer", "kivy-deps.sdl2", "oscpy",]
undeclared_deps = [ "AppKit", "Image", "Leap", "__main__", "android", "android_mixer", "certifi", "coverage", "cv2", "dbus", "enchant", "ffmpeg", "flask", "gi", "gimpfu", "gobject", "ios", "jnius", "kivy_deps", "mock", "numpy", "opencv", "picamera", "pygame", "pyobjus", "pytest_trio", "redis", "setuptools", "smb", "testsuite", "trio", "twisted", "watchdog", "win32api", "win32con", "win32file", "win32gui",]
unused_deps = [ "Kivy-Garden", "flake8", "funcparserlib", "kivy-deps.angle", "kivy-deps.glew", "kivy-deps.glew-dev", "kivy-deps.gstreamer", "kivy-deps.gstreamer-dev", "kivy-deps.sdl2", "kivy-deps.sdl2-dev", "pre-commit", "pypiwin32", "pytest-benchmark", "pytest-cov", "pytest-timeout", "sphinx", "sphinxcontrib-actdiag", "sphinxcontrib-blockdiag", "sphinxcontrib-jquery", "sphinxcontrib-nwdiag", "sphinxcontrib-seqdiag",]

[launching_fawltydeps.settings]
actions = [ "check_undeclared", "check_unused",]
output_format = "json"
code = [ ".repositories/Kivy/kivy",]
deps = [ ".repositories/Kivy/kivy",]
pyenvs = [ ".repositories/Kivy/kivy/venv",]
ignore_undeclared = []
ignore_unused = []
install_deps = false
verbosity = 0
custom_mapping_file = []
