[project]
name = "pingouin"
source_url = "https://github.com/raphaelvallat/pingouin.git"
pingouin_version = "0.5.3"

[launching_fawltydeps]
fawltydeps_version = "0.13.0"

[experiment_result]
"number of warnings" = 0
imports = [ "sklearn", "seaborn", "pandas_flavor", "scipy", "mpmath", "statsmodels", "tabulate", "pytest", "numpy", "outdated", "datamatrix", "matplotlib", "pandas",]
declared_deps = []
undeclared_deps = [ "datamatrix", "matplotlib", "mpmath", "numpy", "outdated", "pandas", "pandas_flavor", "pytest", "scipy", "seaborn", "sklearn", "statsmodels", "tabulate",]
unused_deps = []

[launching_fawltydeps.settings]
actions = [ "check_undeclared", "check_unused",]
output_format = "json"
code = [ ".repositories/pingouin/pingouin",]
deps = [ ".repositories/pingouin/pingouin",]
pyenvs = [ ".repositories/pingouin/pingouin",]
ignore_undeclared = []
ignore_unused = []
install_deps = false
verbosity = 0
custom_mapping_file = []
