[project]
name = "scipy"
source_url = "https://github.com/scipy/scipy.git"
scipy_version = "1.11.2"

[launching_fawltydeps]
fawltydeps_version = "0.13.0"

[experiment_result]
"number of warnings" = 400
imports = [ "sympy", "pythran", "mpmath", "pytest", "torch", "packaging", "pytest_timeout", "matplotlib", "platformdirs", "sphinx", "pybind11", "Cython", "pooch", "scikits", "numpy", "threadpoolctl", "psutil", "hypothesis", "cffi", "sksparse", "cupy",]
declared_deps = [ "numpy", "pytest", "pytest-cov", "pytest-timeout", "pytest-xdist", "asv", "mpmath", "gmpy2", "threadpoolctl", "scikit-umfpack", "pooch", "sphinx", "pydata-sphinx-theme", "sphinx-design", "matplotlib", "numpydoc", "jupytext", "myst-nb", "pooch", "mypy", "typing_extensions", "types-psutil", "pycodestyle", "ruff", "cython-lint", "rich-click", "click", "doit", "pydevtool",]
undeclared_deps = [ "Cython", "cffi", "cupy", "hypothesis", "packaging", "platformdirs", "psutil", "pybind11", "pythran", "scikits", "sksparse", "sympy", "torch",]
unused_deps = [ "asv", "click", "cython-lint", "doit", "gmpy2", "jupytext", "mypy", "myst-nb", "numpydoc", "pycodestyle", "pydata-sphinx-theme", "pydevtool", "pytest-cov", "pytest-xdist", "rich-click", "ruff", "scikit-umfpack", "sphinx-design", "types-psutil", "typing_extensions",]

[launching_fawltydeps.settings]
actions = [ "check_undeclared", "check_unused",]
output_format = "json"
code = [ ".repositories/scipy/scipy",]
deps = [ ".repositories/scipy/scipy",]
pyenvs = [ ".repositories/scipy/scipy",]
ignore_undeclared = []
ignore_unused = []
install_deps = false
verbosity = 0
custom_mapping_file = []
